# Generated by Django 3.2.8 on 2022-01-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='業務種別')),
            ],
        ),
        migrations.CreateModel(
            name='TodoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='処理状況')),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, help_text='作成物の対象期間や属性などの詳細を記入してください', verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(help_text='【社名】を記載してください', max_length=30, verbose_name='タスク名'),
        ),
    ]
